import argparse
import array
import asyncio
import json
import os
import subprocess
import wave

import edge_tts

parser = argparse.ArgumentParser(description='Generate Edge TTS WAV cues and voice.js.')
parser.add_argument('--voice', default='en-US-GuyNeural')
parser.add_argument('--rate', default='-5%')
parser.add_argument('--narration', default='narration.json')
parser.add_argument('--out', default='voice')
parser.add_argument('--force', action='store_true')
args = parser.parse_args()


async def generate(text, mp3_path):
    await edge_tts.Communicate(text, args.voice, rate=args.rate).save(mp3_path)


os.makedirs(args.out, exist_ok=True)
voice_files = []
for scene in json.load(open(args.narration, encoding='utf-8')):
    lines = []
    for index, (spoken, subtitle, *rest) in enumerate(scene['lines']):
        wav_path = os.path.join(args.out, f"{scene['scene']}-{index}.wav")
        mp3_path = wav_path + '.mp3'
        if args.force or not os.path.exists(wav_path):
            asyncio.run(generate(spoken, mp3_path))
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', mp3_path, '-ac', '1', '-ar', '24000', '-c:a', 'pcm_s16le', wav_path], check=True)
            os.remove(mp3_path)
        with wave.open(wav_path, 'rb') as audio:
            sample_rate = audio.getframerate()
            samples = array.array('h', audio.readframes(audio.getnframes()))
        envelope = []
        for start in range(0, len(samples), 1000):
            chunk = samples[start:start + 1000]
            rms = (sum(sample * sample for sample in chunk) / max(1, len(chunk))) ** .5 / 32768
            envelope.append(round(rms, 3))
        duration = round(len(samples) / sample_rate, 3)
        lines.append({'file': wav_path.replace('\\', '/'), 'dur': duration, 'env': envelope})
        print(scene['scene'], index, duration, 's')
    voice_files.append({'scene': scene['scene'], 'lines': lines})

with open('voice.js', 'w', encoding='utf-8', newline='\n') as output:
    output.write("'use strict';\n// Generated by tts_edge.py. Audio clips are merged with the scene cues in scenes.js.\n")
    output.write('const VOICE_FILES = ' + json.dumps(voice_files, ensure_ascii=False) + ';\n')
print('total speech', round(sum(line['dur'] for scene in voice_files for line in scene['lines']), 1), 's')